#! /bin/bash
# ON/OFF-button for Netflix in Galliumos

if [ -f /tmp/netfix ] ; then
 kill $(cat /tmp/netfix )
 rm -f /tmp/netfix 
 xrandr --output LVDS1 --gamma 1:1:1 --brightness 1.0
 xbacklight = $(cat /tmp/backlight)
else
 echo $(xbacklight) > /tmp/backlight
 noko-auto-brit-xbacklight&
 $! > /tmp/netfix
 xrandr --output LVDS1 --gamma 1.2:1.1:1.0 --brightness 1.1
fi
