#! /bin/bash
# This is from Chromebook with GalliumOs

if [ "$1" == "" ] ; then base="0.3" ; else base="$1" ; fi
while true ; do
 scrot /tmp/scave.jpg
 a=$(identify -format "%[mean]" /tmp/scave.jpg)
 b=$(echo "scale=2 ; ($base + 2000 / $a) * 70 " | bc )
 xbacklight = "$b"
# echo $a $b
 sleep 0.1
done



